// The How-to layers for the gallery cards (grip/GRIP-AND-FEEL-ARCHITECTURE.md 2.1-2.7, 5.2, 5.3):
//   zoom chips ("Look closer"), hand and posture close-ups, "Where you should feel it", "Set it up", "Risks and when
//   to stop", then the owner's disclaimer. No sources, evidence labels or contacts in the UI (owner 2026-09-30, LR-23).
// Imported by build-page.mjs. Content comes from exercises/<id>.howto.mjs (the verified cards). The close-up drawings
// come from each exercise's own reviewed render script (exercises/<id>.howto-render.mjs or howto/render-<id>.mjs):
// the script's drawing functions are loaded WITHOUT its screenshot run (the source is cut where the Playwright run
// starts, written to artifact/.gen/ and imported), so the page shows exactly the drawings those scripts check.
// Nothing in engine/, exercises/ or howto/ is changed by this file.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { renderFeelMap, renderFeelLegend, FEEL_CSS } from '../engine/feelmap.mjs';
import { HAND_CSS } from '../engine/hand.mjs';
import { RED_FLAG, RED_FLAG_SHOULDER, RED_FLAG_KNEE, RED_FLAG_ELBOW, DISCLAIMER } from '../howto/shared.mjs';
import * as SHARED from '../howto/shared.mjs';
import { lintAll, formatViolations, FEEL_ROWS_MAX, SETUP_MAX_STEPS } from './copy-lint.mjs';
// Supervisor 2026-09-30: with the compact caps every row and step shows; a red-flag row or a safety step never
// sits behind a "Show more" button. The collapse code stays for any list longer than its cap (the lint forbids that).
const FEEL_VISIBLE = FEEL_ROWS_MAX, SETUP_VISIBLE = SETUP_MAX_STEPS;
import { PLATE_CSS } from '../engine/index.mjs';
import { allThemesCss } from '../engine/themes.mjs';

const here = dirname(fileURLToPath(import.meta.url)), root = join(here, '..'), genDir = join(here, '.gen');
const TOKENS = readFileSync(join(root, 'engine', 'tokens.css'), 'utf8');
const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const escR = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/"/g, '&quot;');   // the render scripts' esc

export const HOWTO_IDS = ['dumbbell_lateral_raise', 'barbell_back_squat', 'pull_up', 'hanging_leg_raise', 'lat_pulldown', 'seated_cable_row', 'leg_press', 'machine_chest_press'];
const RENDERER = {
  machine_chest_press: 'exercises/machine_chest_press.howto-render.mjs',
  barbell_back_squat: 'exercises/barbell_back_squat.howto-render.mjs',
  leg_press: 'exercises/leg_press.howto-render.mjs',
  dumbbell_lateral_raise: 'howto/render-dumbbell_lateral_raise.mjs',
  hanging_leg_raise: 'howto/render-hanging_leg_raise.mjs',
  lat_pulldown: 'howto/render-lat_pulldown.mjs',
  pull_up: 'howto/render-pull_up.mjs',
  seated_cable_row: 'howto/render-seated_cable_row.mjs',
};
const API = ['handZoom', 'postureZoom', 'zoomSection', 'chipRow', 'PAGES', 'CSS', 'ZCSS', 'howto'];

/** Load a render script's drawing functions without running its Playwright pass. */
async function loadRenderer(id) {
  const file = join(root, RENDERER[id]), url = pathToFileURL(file).href;
  let src = readFileSync(file, 'utf8');
  const cut = src.indexOf('const { chromium } = createRequire(');
  if (cut < 0) throw new Error(`${id}: render script has no Playwright start to cut at`);
  src = src.slice(0, cut)
    .replace(/import\.meta\.url/g, JSON.stringify(url))
    .replace(/(from\s+|import\s*\(\s*)'(\.{1,2}\/[^']+)'/g, (m, pre, spec) => `${pre}'${new URL(spec, url).href}'`);
  src += `\nexport const __api = { ${API.map(n => `${n}: typeof ${n} === 'undefined' ? undefined : ${n}`).join(', ')} };\n`;
  mkdirSync(genDir, { recursive: true });
  const out = join(genDir, `${id}.mjs`);
  writeFileSync(out, `// GENERATED by artifact/howto-layers.mjs from ${RENDERER[id]} (drawing part only). Do not edit.\n${src}`);
  return (await import(pathToFileURL(out).href)).__api;
}

/* ---------------------------------------------------------------- helpers ---------------------------------------- */
/** Give every id a fragment defines a per-card prefix, and follow every reference to it (url(#), href, aria-*). */
function prefixIds(html, pre) {
  const ids = new Set([...html.matchAll(/\sid="([^"]+)"/g)].map(m => m[1]));
  const map = id => ids.has(id) ? pre + id : id;
  return html
    .replace(/(\sid=")([^"]+)"/g, (m, a, b) => `${a}${map(b)}"`)
    .replace(/url\((['"]?)#([^)'"]+)\1\)/g, (m, q, b) => `url(${q}#${map(b)}${q})`)
    .replace(/((?:xlink:)?href=")#([^"]+)"/g, (m, a, b) => `${a}#${map(b)}"`)
    .replace(/(aria-(?:labelledby|describedby|controls)=")([^"]+)"/g, (m, a, b) => `${a}${b.split(/\s+/).map(map).join(' ')}"`);
}
const splitTop = s => { const out = []; let d = 0, cur = ''; for (const ch of s) { if (ch === '(') d++; if (ch === ')') d--; if (ch === ',' && !d) { out.push(cur); cur = ''; } else cur += ch; } out.push(cur); return out; };
/** Scope a render script's page CSS to one card's close-ups (page-level rules and @font-face are dropped). */
function scopeCss(css, scope) {
  css = css.replace(/\/\*[\s\S]*?\*\//g, '');
  let out = '', i = 0;
  while (i < css.length) {
    const open = css.indexOf('{', i);
    if (open < 0) break;
    const head = css.slice(i, open).trim();
    let depth = 1, j = open + 1;
    while (depth && j < css.length) { if (css[j] === '{') depth++; else if (css[j] === '}') depth--; j++; }
    const body = css.slice(open + 1, j - 1);
    if (/^@(media|supports)/.test(head)) out += `${head}{${scopeCss(body, scope)}}`;
    else if (/^@keyframes/.test(head)) out += `${head}{${body}}`;
    else if (!head.startsWith('@')) {
      const sels = splitTop(head).map(s => s.trim()).filter(s => s && !/^(html|body|:root)\b/.test(s));
      if (sels.length) out += `${sels.map(s => `${scope} ${s}`).join(',')}{${body.trim()}}\n`;
    }
    i = j;
  }
  return out;
}
const SHARED_CSS = [TOKENS, allThemesCss(), PLATE_CSS, HAND_CSS, FEEL_CSS];
const rendererCss = (api, scope) => {
  let css = api.ZCSS ?? api.CSS ?? '';
  for (const s of SHARED_CSS) css = css.split(s).join('');
  css = css.split('.pager-btn[aria-selected="true"]').join('.pager-btn[aria-pressed="true"]');   // see cleanZoom: pager
  return scopeCss(css, scope);
};

/* ---------------------------------------------------------------- icons (the app's base() style) ------------------ */
const ic = (d, s = 18) => `<svg width="${s}" height="${s}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="${(1.5 * 24 / s).toFixed(2)}" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${d}</svg>`;
const I = {
  x: s => ic('<path d="M6 6l12 12M18 6L6 18"/>', s), chev: s => ic('<path d="M9 6l6 6-6 6"/>', s),
  down: s => ic('<path d="M6 9l6 6 6-6"/>', s), alert: s => ic('<path d="M12 8v5M12 16.5v.5"/><circle cx="12" cy="12" r="9"/>', s),
  arrow: s => ic('<path d="M5 12h13M13 7l5 5-5 5"/>', s), up: s => ic('<path d="M12 19V6M7 11l5-5 5 5"/>', s), ext: s => ic('<path d="M14 5h5v5M19 5l-8 8"/><path d="M18 14v4a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h4"/>', s),
};

/* ---------------------------------------------------------------- zooms ------------------------------------------ */
/** TalkBack (architecture 2.5): each half of a right/wrong drawing is its own role="img" with its own text. A drawing
 *  whose single label reads "<camera>. Right: <a> Wrong: <b>" and whose halves are marked (<g class="h-panel right">
 *  from engine/hand.mjs, <g class="zx-half wrong"> from the render scripts) becomes a group labelled by the camera,
 *  holding two images, "Right: <a>" and "Wrong: <b>". Its printed words (Right, Wrong, notes, values) are hidden from
 *  the reader, since the two image labels already say them. Throws if a paired label has no marked halves. */
export function splitHalves(html, where = '') {
  let out = '', i = 0;
  for (;;) {
    const a = html.indexOf('<svg class="hand-svg', i);
    if (a < 0) break;
    let depth = 0, j = a;
    for (const m of html.slice(a).matchAll(/<svg\b|<\/svg>/g)) { depth += m[0] === '</svg>' ? -1 : 1; if (!depth) { j = a + m.index + 6; break; } }
    let svg = html.slice(a, j);
    const open = svg.slice(0, svg.indexOf('>') + 1), lab = open.match(/aria-label="([^"]*)"/)?.[1] ?? '';
    const m = lab.match(/^([\s\S]*?)\s*Right: ([\s\S]*?)\s*Wrong: ([\s\S]*)$/);
    if (m && / role="img"/.test(open)) {
      const halves = svg.match(/<g class="(?:h-panel|zx-half) (?:right|wrong)">/g) ?? [];
      if (halves.length !== 2) throw new Error(`${where}: a right/wrong drawing without two marked halves (${halves.length})`);
      const cam = m[1].replace(/\.$/, '');
      svg = svg.replace(open, open.replace(' role="img"', ' role="group"').replace(/aria-label="[^"]*"/, `aria-label="${cam}"`))
        .replace(/<text /g, '<text aria-hidden="true" ')
        .replace(/<g class="((?:h-panel|zx-half) (right|wrong))">/g, (x, cls, side) => `<g class="${cls}" role="img" aria-label="${side === 'right' ? 'Right: ' + m[2] : 'Wrong: ' + m[3]}">`);
    }
    out += html.slice(i, a) + svg; i = j;
  }
  return out + html.slice(i);
}
/** Tidy one render-script zoom section for the card: its own heading/back row and chip row go (the card draws them
 *  once for every exercise), the long wrist-limit hint goes (one plain line of copy under a hand), every button gets
 *  type="button", and the "This is usually why" link and the page tabs get data hooks for the page script. */
function cleanZoom(html, { api, howto, zoom, pageIdx }) {
  if (api.chipRow) html = html.split(api.chipRow(zoom.key)).join('');
  html = html
    .replace(/<div class="ztop">[\s\S]*?<\/h3><\/div>/, '')
    .replace(/<div class="zoom-top">[\s\S]*?<\/h3><\/div>/, '')
    .replace(/\srole="region" aria-labelledby="zh-[^"]*"/, '');
  const lim = howto.handling?.wrist?.limitText;
  if (lim) html = html.split(`<p class="hint limit">${escR(lim)}</p>`).join('');
  html = html.replace(/<button(?![^>]*\stype=)/g, '<button type="button"');
  if (zoom.feelRow) html = html.replace(/<button type="button" class="(feellink|z-feelrow)"/g, `<button type="button" class="$1" data-feelrow="${esc(zoom.feelRow)}"`);
  // Page buttons: each page carries its own copy of the pager (only the shown page's copy is visible), so they are plain
  // toggle buttons in a group, not an ARIA tablist (a tablist needs one list, roving tabindex and arrow keys).
  html = html.replace(/<div class="pager" role="tablist"/g, '<div class="pager" role="group"')
    .replace(/(<button type="button" class="pager-btn") role="tab" aria-selected=/g, '$1 aria-pressed=');
  if (/role="tab|aria-selected/.test(html)) throw new Error(`${howto.id}/${zoom.key}: tab roles left in a close-up`);
  let k = 0;
  html = html.replace(/<button type="button" class="pager-btn"/g, () => `<button type="button" class="pager-btn" data-page="${k}" id="zb-${zoom.key}-p${pageIdx}-tab${k++}"`);
  html = html.replace(/<button type="button" class="(feellink|z-feelrow)"/g, `<button type="button" id="zb-${zoom.key}-p${pageIdx}-why" class="$1"`);
  html = splitHalves(html, `${howto.id}/${zoom.key}`);
  if (/<button(?![^>]*\sid=)/.test(html)) throw new Error(`${howto.id}/${zoom.key}: a close-up button without an id`);
  if (/ztop|zoom-top|class="chips"|zoom-chips/.test(html)) throw new Error(`${howto.id}/${zoom.key}${pageIdx != null ? ' p' + pageIdx : ''}: chrome not stripped`);
  return html;
}
function zoomPanels(pre, api, howto) {
  return howto.zooms.map(z => {
    let pages;
    if (api.zoomSection) pages = [api.zoomSection(z)];
    else if (z.kind === 'hand') pages = api.PAGES ? api.PAGES.map(p => api.handZoom(p.key)) : [api.handZoom()];
    else pages = [api.postureZoom(z)];
    const body = pages.map((h, i) => `<div class="zx-page" data-page="${i}"${i ? ' hidden' : ''}>${cleanZoom(h, { api, howto, zoom: z, pageIdx: i })}</div>`).join('');
    const hid = `${pre}-zoom-${z.key}-h`;
    return `<div class="zx" id="${pre}-zoom-${z.key}" data-zoom="${esc(z.key)}" role="region" aria-labelledby="${hid}" hidden>`
      + `<div class="zx-top"><h4 class="zx-h" id="${hid}" tabindex="-1">${esc(z.heading)}</h4>`
      + `<button type="button" class="zx-close" id="${pre}-zoom-${z.key}-close" aria-label="Close the close-up and show the plate">${I.x(18)}</button></div>`
      + `<div class="hx hx-${pre}">${prefixIds(body, `${pre}-z-`)}</div></div>`;
  }).join('');
}
const chipKeys = howto => howto.chips ?? [...howto.zooms.map(z => z.key), 'feel'];
function chipRow(pre, howto) {
  const keys = chipKeys(howto);
  if (keys.length > 4) throw new Error(`${howto.id}: ${keys.length} chips (max 4)`);
  const handFirst = ['push', 'pull', 'hang', 'hold', 'curl', 'on-body'].includes(howto.handling?.archetype);
  if (handFirst && keys[0] !== 'hand') throw new Error(`${howto.id}: load goes through the hands, Hand must be the first chip`);
  return `<div class="zx-chips-wrap"><span class="eyebrow" id="${pre}-look">Look closer</span><div class="zx-chips" role="group" aria-labelledby="${pre}-look">`
    + keys.map(k => k === 'feel'
      ? `<button type="button" class="zx-chip" id="${pre}-chip-feel" data-feel aria-label="Where to feel it">Feel it</button>`
      : (z => `<button type="button" class="zx-chip" id="${pre}-chip-${k}" data-zoom="${esc(k)}" aria-pressed="false" aria-controls="${pre}-zoom-${k}">${esc(z.chip)}${z.chipCaption ? `<span class="zx-chip-cap">${esc(z.chipCaption)}</span>` : ''}</button>`)(howto.zooms.find(z => z.key === k))).join('')
    + `</div></div>`;
}

/* ---------------------------------------------------------------- feel ------------------------------------------- */
const PAIN_NAMES = [[/^hand-/, 'wrists and hands'], [/^elbow-/, 'elbows'], [/^knee-/, 'knees'], [/^nape$/, 'back of the neck']];
function feelSection(pre, howto, M) {
  const F = howto.feel, ids = x => x.muscleId;
  const rest = renderFeelMap({ primary: F.primary, secondary: F.secondary, views: ['front', 'back'], id: `${pre}-feel`, shimmer: true });
  const watchIds = new Set(F.watch.map(ids)), priIds = new Set(F.primary.map(ids));
  const marks = [[], []];
  const rows = F.rows.map(r => {
    const watch = (r.at?.muscles ?? []).filter(m => watchIds.has(m) && !priIds.has(m));
    const pain = r.at?.parts ?? [];
    let label = rest.label;
    if (watch.length || pain.length) {
      const m = renderFeelMap({ primary: F.primary, secondary: F.secondary, avoid: watch, pain, views: ['front', 'back'], id: `${pre}-feel-${r.key}`, shimmer: false });
      label = m.label;
      const pn = [...new Set(pain.map(p => PAIN_NAMES.find(([re]) => re.test(p))?.[1] ?? p))];
      if (pn.length) label += ` Marked: ${pn.join(' and ')}.`;
      m.svg.split('</figure>').slice(0, 2).forEach((v, vi) => {
        const w = v.match(/<g class="feel-watch">[\s\S]*?<\/g>/)?.[0] ?? '', p = v.match(/<g class="feel-pain">[\s\S]*?<\/g>/)?.[0] ?? '';
        if (w || p) marks[vi].push(`<g class="feel-mark" data-row="${esc(r.key)}">${w.replace('class="feel-watch"', 'class="feel-quiet"')}${p}${w}</g>`);
      });
    }
    return { r, watch, pain, label };
  });
  let k = 0;
  const mapHtml = rest.html.replace(/<\/svg>/g, s => `${marks[k++]?.join('') ?? ''}${s}`)
    .replace('data-feel-map>', `data-feel-map id="${pre}-feel-map" data-rest-label="${esc(rest.label)}">`);
  const legend = renderFeelLegend({ avoid: true }).replace(/<span>(<svg class="feel-sw sw-watch)/, '<span class="lg-watch" hidden>$1')
    .replace(/<\/div>$/, `<span class="lg-pain" hidden><svg class="feel-sw sw-pain" viewBox="0 0 14 14" aria-hidden="true"><rect x="1.5" y="1.5" width="11" height="11" rx="3"/></svg>Where it may hurt</span></div>`);
  // plan 2.4 / HT9-A3: ONE red-flag node per sheet, in "Risks and when to stop". A row that needs it (architecture 2.7,
  // S6) links to it instead of printing a second copy.
  const RF = { true: 'wrist', shoulder: 'shoulder', knee: 'knee', elbow: 'elbow' };
  const zoomChip = key => howto.zooms.find(z => z.key === key)?.chip;
  const rowsHtml = rows.map(({ r, watch, pain, label }, i) => {
    const flag = r.redFlag ? RF[r.redFlag] : null;
    if (r.redFlag && !flag) throw new Error(`${howto.id}: row ${r.key} red flag ${r.redFlag} missing`);
    return `<li class="fr" data-row="${esc(r.key)}"${i >= FEEL_VISIBLE ? ' data-more hidden' : ''}>`
      + `<button type="button" class="fr-btn" id="${pre}-row-${r.key}" aria-expanded="false" aria-controls="${pre}-row-${r.key}-body" data-label="${esc(label)}"${watch.length ? ' data-watch' : ''}${pain.length ? ' data-pain' : ''}>`
      + `<span>${esc(r.where)}</span>${I.down(18)}</button>`
      + `<div class="fr-body" id="${pre}-row-${r.key}-body" hidden><p><b>Usually means</b>${esc(r.means)}</p><p><b>Fix</b>${esc(r.fix)}</p>`
      + (r.zoom ? `<button type="button" class="fr-show" id="${pre}-row-${r.key}-show" data-zoom="${esc(r.zoom)}">Show me the ${esc(zoomChip(r.zoom).toLowerCase())}${I.arrow(16)}</button>` : '')
      + (flag ? `<button type="button" class="rf-link" id="${pre}-row-${r.key}-flag" data-flag="${flag}" aria-controls="${pre}-redflag-${flag}">${I.alert(16)}When to get it checked</button>` : '')
      + `</div></li>`;
  }).join('');
  const more = F.rows.length - FEEL_VISIBLE;
  const txt = (F.textOnly ?? []).map(m => m.plain).join(' ');
  return `<section class="hw-sec feel" id="${pre}-feel" aria-labelledby="${pre}-feel-h">`
    + `<h4 class="eyebrow" id="${pre}-feel-h" tabindex="-1">Where you should feel it</h4>`
    + `<p class="feel-lead">${esc(F.feelLine)}</p>${mapHtml}${legend}${txt ? `<p class="feel-note">${esc(txt)}</p>` : ''}`
    + `<h5 class="eyebrow fr-head">If you feel it in…</h5><ul class="fr-list">${rowsHtml}</ul>`
    + (more > 0 ? `<button type="button" class="fr-more" id="${pre}-feel-more" aria-expanded="false" data-n="${more}">Show ${more} more</button>` : '')
    + `</section>`;
}

/* ---------------------------------------------------------------- setup and the disclaimer ---------------------- */
function setupSection(pre, howto) {
  const steps = howto.setup, zoomChip = key => howto.zooms.find(z => z.key === key)?.chip;
  const more = steps.length - SETUP_VISIBLE;
  return `<section class="hw-sec setup" id="${pre}-setup" aria-labelledby="${pre}-setup-h"><h4 class="eyebrow" id="${pre}-setup-h">Set it up</h4>`
    + `<ol class="st-list">${steps.map((s, i) => `<li${i >= SETUP_VISIBLE ? ' data-more hidden' : ''}><span class="st-n" aria-hidden="true">${i + 1}</span><div><p>${esc(s.text)}</p>`
      + (s.zoom && zoomChip(s.zoom) ? `<button type="button" class="st-show" id="${pre}-step-${i + 1}-show" data-zoom="${esc(s.zoom)}">Show me the ${esc(zoomChip(s.zoom).toLowerCase())}${I.arrow(16)}</button>` : '')
      + `</div></li>`).join('')}</ol>`
    + (more > 0 ? `<button type="button" class="fr-more st-more" id="${pre}-setup-more" aria-expanded="false" data-n="${steps.length}" data-all>All ${steps.length} steps</button>` : '')
    + `</section>`;
}
const disclaimerNode = pre => `<p class="ht-disclaimer" id="${pre}-disclaimer">${esc(DISCLAIMER)}</p>`;

/* ---------------------------------------------------------------- grip and handling mistakes (plan 2.4 item 4) ----- */
function gripSection(pre, howto) {
  const h = howto.handling;
  if (!h?.gripLine) throw new Error(`${howto.id}: no grip line`);
  const zoomChip = key => howto.zooms.find(z => z.key === key)?.chip;
  const limit = h.wrist?.limitText, sore = h.handleChoice?.sore;
  const items = howto.mistakes.map(m => `<li class="hm"><p class="hm-t">${I.x(16)}<b>${esc(m.title)}</b></p><p class="hm-fix"><span class="sr-only">Fix: </span>${esc(m.fix)}</p>`
    + (m.zoom && zoomChip(m.zoom) ? `<button type="button" class="st-show hm-show" id="${pre}-mis-${m.key}-show" data-zoom="${esc(m.zoom)}">Show me the ${esc(zoomChip(m.zoom).toLowerCase())}${I.arrow(16)}</button>` : '')
    + `</li>`).join('');
  return `<section class="hw-sec grip" id="${pre}-grip" aria-labelledby="${pre}-grip-h"><h4 class="eyebrow" id="${pre}-grip-h">Grip</h4>`
    + `<p class="grip-lead">${esc(h.gripLine)}</p>`
    + (limit ? `<p class="grip-note">${esc(limit)}</p>` : '') + (sore ? `<p class="grip-note">${esc(sore)}</p>` : '')
    + `<h5 class="eyebrow hm-head" id="${pre}-mis-h">Common handling mistakes</h5><ul class="hm-list" aria-labelledby="${pre}-mis-h">${items}</ul></section>`;
}

/* ---------------------------------------------------------------- risks and when to stop (plan 2.4 item 7) ------- */
function risksSection(pre, howto) {
  const flags = howto.riskFlags ?? ['wrist'];
  const FLAG = { wrist: RED_FLAG, shoulder: RED_FLAG_SHOULDER, knee: RED_FLAG_KNEE, elbow: RED_FLAG_ELBOW };
  const rowFlags = new Set(howto.feel.rows.filter(r => r.redFlag).map(r => r.redFlag === true ? 'wrist' : r.redFlag));
  for (const f of rowFlags) if (!flags.includes(f)) throw new Error(`${howto.id}: a row links to the ${f} red flag, but Risks does not show it`);
  for (const f of flags) {
    if (!rowFlags.has(f)) throw new Error(`${howto.id}: Risks shows the ${f} red flag, but no row links to it`);
    for (const s of FLAG[f]?.claim.sources ?? []) if (!howto.sources.includes(s)) throw new Error(`${howto.id}: the ${f} red flag's source ${s} is not in the sheet's sources`);
  }
  const block = f => { const F = FLAG[f]; if (!F) throw new Error(`${howto.id}: no shared red flag ${f}`);
    return `<div class="redflag" role="note" id="${pre}-redflag-${f}" tabindex="-1">${I.alert(16)}<div><p class="rf-name">${esc(F.name)}</p><p>${esc(F.now)}</p><p>${esc(F.doctor)}</p></div></div>`; };
  return `<section class="hw-sec risks" id="${pre}-risks" aria-labelledby="${pre}-risks-h"><h4 class="eyebrow" id="${pre}-risks-h">Risks and when to stop</h4>`
    + `<ul class="rk-list">${howto.risks.map(r => `<li>${esc(r.text)}</li>`).join('')}</ul>`
    + flags.map(block).join('') + `</section>`;
}

/** Mistake view, push exercises (architecture 2.1: load straight down the forearm, the wrist fault matters most): one
 *  quiet line under the tempo strip, outside the approved plate block, that opens the hand close-up. Shown by the page
 *  script only while Mistake is on. */
function alsoRow(pre, howto) {
  if (howto.handling?.archetype !== 'push') return '';
  const z = howto.zooms.find(q => q.kind === 'hand');
  if (!z) throw new Error(`${howto.id}: push exercise without a hand close-up`);
  return `<p class="ht-also" id="${pre}-also" hidden><span>Also check your wrist:</span><button type="button" class="ht-also-btn" id="${pre}-also-hand" data-zoom="${esc(z.key)}" aria-controls="${pre}-zoom-${esc(z.key)}">${esc(z.chip)}${z.chipCaption ? `, ${esc(z.chipCaption.toLowerCase())}` : ''}${I.up(16)}</button></p>`;
}

/* ---------------------------------------------------------------- public ----------------------------------------- */
/** Build every card's How-to layers. Returns { [cardId]: { howto, plate, chips, zooms, feel, setup, risks } } and CSS. */
export async function buildHowtoLayers() {
  // Copy lint first (architecture 6.2 with the owner's 2026-09-30 limits, artifact/copy-lint.mjs): every failure on
  // every sheet, in one error. It only reads the specs, so a clean run changes no output.
  const mods = [];
  for (const id of HOWTO_IDS) mods.push(await import(pathToFileURL(join(root, 'exercises', `${id}.howto.mjs`)).href));
  const { violations } = lintAll(mods, SHARED);
  if (violations.length) throw new Error(`copy lint: ${violations.length} problems\n${formatViolations(violations)}`);
  const apis = {};
  for (const id of HOWTO_IDS) apis[id] = await loadRenderer(id);   // all loaded first: the leg-raise script's stomach
  // region fix (howto/render-hanging_leg_raise.mjs REGION_FIX) then applies to every map on the page, not to some
  const out = {}, css = [];
  for (const id of HOWTO_IDS) {
    const M = await import(pathToFileURL(join(root, 'exercises', `${id}.howto.mjs`)).href);
    const howto = M.default, api = apis[id];
    const cardId = id === 'dumbbell_lateral_raise' ? 'lateral_raise' : id;
    const pre = cardId.replace(/_/g, '-');
    const chips = chipRow(pre, howto), zooms = zoomPanels(pre, api, howto);
    // sheet order below the approved block (plan 2.4, 3-7): Look closer, grip + handling mistakes, feel, setup, risks,
    // then the disclaimer (once, last)
    const after = [alsoRow(pre, howto), chips, gripSection(pre, howto), feelSection(pre, howto, M), setupSection(pre, howto),
      risksSection(pre, howto), disclaimerNode(pre)].join('\n  ');
    out[cardId] = { howto, zooms, after };
    css.push(`/* close-ups: ${RENDERER[id]} */\n${rendererCss(api, `.hx-${pre}`)}`);
  }
  return { layers: out, css: css.join('\n') };
}

/** One hidden dot pattern for the posture crops' background (the render scripts put it on their page). Inside the
 *  themed band, so its --border-subtle follows the app theme. */
export const ZDOTS = `<svg width="0" height="0" style="position:absolute" aria-hidden="true" focusable="false"><defs><pattern id="zdots" width="16" height="16" patternUnits="userSpaceOnUse"><rect x="7.5" y="7.5" width="1" height="1" class="zdot"/></pattern></defs></svg>`;
export { FEEL_CSS, HAND_CSS };
