// HT-8: "Where you should feel it" (plan 2.4 item 5, 2.5). Inserts golden B's pre-rendered section string once
// (feel-<chromeId>.ts, generated by tools/plates/gen/feel.mjs) and binds golden B's behaviour (useFeelMap).
// Mount (plan 2.5): after two animation frames or when the section comes within one sheet-panel height, whichever is
// later; the chunk loads then, so the map is in before it is seen and golden B's timing starts from its own observer.
// A "Feel it" chip or "This is usually why" before that loads it at once and is replayed after the mount (HT-10's
// finding on #166: the controller's own listeners exist only once the section is in).
import { useLayoutEffect, useMemo, useRef, useState } from 'preact/hooks';
import type { SectionProps } from './index';
import { howToLoadFailed } from '../lazy';
import { useFeelMap, type FeelPending } from '../feel/useFeelMap';
import { listen } from '../events';
import { chromeIdOf } from '../PlateView';
import '../css/feel.css';

export interface FeelChunk { readonly default: { readonly id: string; readonly pre: string; readonly section: string } }
const CHUNKS = import.meta.glob<FeelChunk>('../../../howto/generated/feel-*.ts');
/** The chunk for a How-to: feel-<chromeId> (golden B's card id prefix, e.g. lateral-raise; supervisor ruling, #119). */
export const feelPath = (chromeId: string) => `../../../howto/generated/feel-${chromeId}.ts`;

/** Resolves once two frames have passed and `el` is within one `root` height of `root`'s visible area. `root` is the
 *  sheet's scrolling panel: with the viewport as root, the panel clips the section before the margin applies. */
export function whenNear(el: Element, done: () => void, root: Element | null = null): () => void {
  let frames = false, near = false, fired = false, raf = 0;
  const go = () => { if (frames && near && !fired) { fired = true; io?.disconnect(); done(); } };
  raf = requestAnimationFrame(() => { raf = requestAnimationFrame(() => { frames = true; go(); }); });
  const io = typeof IntersectionObserver === 'function'
    ? new IntersectionObserver(es => { if (es.some(e => e.isIntersecting)) { near = true; go(); } }, { root, rootMargin: '100% 0px' })
    : null;
  if (io) io.observe(el); else near = true;
  return () => { cancelAnimationFrame(raf); io?.disconnect(); };
}

export function Feel({ howTo }: SectionProps) {
  const host = useRef<HTMLDivElement>(null);
  const pending = useRef<FeelPending | null>(null);
  const [section, setSection] = useState<string | null>(null);
  // a layout effect, so the early listeners are on before the first paint shows the chip
  useLayoutEffect(() => {
    const load = CHUNKS[feelPath(chromeIdOf(howTo))];
    const el = host.current;
    if (!load || !el) return;
    let live = true, started = false;
    const start = () => {
      if (started) return;
      started = true; stop();
      void load().then(m => { if (live) setSection(m.default.section); }).catch(() => { if (live) howToLoadFailed(() => {}); });
    };
    const stop = whenNear(el, start, el.closest('.sheet-panel'));
    // before the mount the controller is not listening: catch the request, load now, replay it in useFeelMap
    const sheet = el.closest('.ht') ?? el.parentElement!;
    const early = (p: FeelPending) => { if (el.querySelector('.feel')) return; pending.current = { ...pending.current, ...p }; start(); };
    const offs = [listen(sheet, 'ht:feel-chip', () => early({ chip: true })), listen(sheet, 'ht:feel-row', d => early({ row: d.row }))];
    return () => { live = false; stop(); offs.forEach(f => f()); };
  }, []);
  // inserted once (memoised; Preact never re-sets it), like the plate strings
  const inner = useMemo(() => (section ? { __html: section } : undefined), [section]);
  useFeelMap(host, section != null, pending);
  return <div class="ht-feel-host" ref={host} dangerouslySetInnerHTML={inner} />;
}
