// HT-4 (HT4-A3 C6): the 153-id coverage table (build plan appendix B / GRIP-AND-FEEL-ARCHITECTURE.md 10).
// Every exercises.json id is either 'approved' (a golden-B reviewed HowToContent exists) or 'pending' with the
// hand archetype appendix B assigns it (provisional; each exercise's own card confirms or changes it, plan 3).
// Generated once by script from appendix B against src/data/exercises.json (every id assigned exactly once, none
// unknown); edited by hand only to record a card's own archetype change, never to make C6 pass.
import type { ContentLibId, HandArchetypeId } from './content-types';

export type CoverageEntry =
  | { readonly status: 'approved' }
  | { readonly status: 'pending'; readonly archetype: HandArchetypeId };

export const COVERAGE: Readonly<Record<ContentLibId, CoverageEntry>> = {
  'lib_machine_chest_press': { status: 'approved' },
  'lib_dumbbell_bench_press': { status: 'pending', archetype: 'push' },
  'lib_barbell_bench_press': { status: 'pending', archetype: 'push' },
  'lib_smith_machine_bench_press': { status: 'pending', archetype: 'push' },
  'lib_incline_machine_press': { status: 'pending', archetype: 'push' },
  'lib_incline_dumbbell_press': { status: 'pending', archetype: 'push' },
  'lib_incline_barbell_bench_press': { status: 'pending', archetype: 'push' },
  'lib_smith_machine_incline_press': { status: 'pending', archetype: 'push' },
  'lib_decline_bench_press': { status: 'pending', archetype: 'push' },
  'lib_cable_chest_press': { status: 'pending', archetype: 'push' },
  'lib_pec_fly': { status: 'pending', archetype: 'hold' },
  'lib_cable_fly': { status: 'pending', archetype: 'hold' },
  'lib_low_to_high_cable_fly': { status: 'pending', archetype: 'hold' },
  'lib_high_to_low_cable_fly': { status: 'pending', archetype: 'hold' },
  'lib_dumbbell_fly': { status: 'pending', archetype: 'hold' },
  'lib_push_up': { status: 'pending', archetype: 'palm-flat' },
  'lib_incline_push_up': { status: 'pending', archetype: 'palm-flat' },
  'lib_weighted_dip': { status: 'pending', archetype: 'push' },
  'lib_shoulder_press': { status: 'pending', archetype: 'push' },
  'lib_dumbbell_shoulder_press': { status: 'pending', archetype: 'push' },
  'lib_barbell_overhead_press': { status: 'pending', archetype: 'push' },
  'lib_smith_machine_shoulder_press': { status: 'pending', archetype: 'push' },
  'lib_arnold_press': { status: 'pending', archetype: 'push' },
  'lib_dumbbell_lateral_raise': { status: 'approved' },
  'lib_cable_lateral_raise': { status: 'pending', archetype: 'hold' },
  'lib_machine_lateral_raise': { status: 'pending', archetype: 'balance' },
  'lib_dumbbell_front_raise': { status: 'pending', archetype: 'hold' },
  'lib_rear_delt_fly': { status: 'pending', archetype: 'pull' },
  'lib_cable_rear_delt_fly': { status: 'pending', archetype: 'hold' },
  'lib_bent_over_dumbbell_rear_delt_fly': { status: 'pending', archetype: 'hold' },
  'lib_face_pull': { status: 'pending', archetype: 'pull' },
  'lib_cable_external_rotation': { status: 'pending', archetype: 'pull' },
  'lib_upright_row': { status: 'pending', archetype: 'pull' },
  'lib_triceps_pushdown': { status: 'pending', archetype: 'push' },
  'lib_rope_triceps_pushdown': { status: 'pending', archetype: 'push' },
  'lib_straight_bar_triceps_pushdown': { status: 'pending', archetype: 'push' },
  'lib_single_arm_triceps_pushdown': { status: 'pending', archetype: 'push' },
  'lib_overhead_cable_triceps_extension': { status: 'pending', archetype: 'push' },
  'lib_dumbbell_overhead_triceps_extension': { status: 'pending', archetype: 'push' },
  'lib_skull_crusher': { status: 'pending', archetype: 'push' },
  'lib_close_grip_bench_press': { status: 'pending', archetype: 'push' },
  'lib_bench_dip': { status: 'pending', archetype: 'palm-flat' },
  'lib_lat_pulldown': { status: 'approved' },
  'lib_close_grip_pulldown': { status: 'pending', archetype: 'pull' },
  'lib_underhand_lat_pulldown': { status: 'pending', archetype: 'pull' },
  'lib_single_arm_lat_pulldown': { status: 'pending', archetype: 'pull' },
  'lib_pull_up': { status: 'approved' },
  'lib_chin_up': { status: 'pending', archetype: 'hang' },
  'lib_assisted_pull_up': { status: 'pending', archetype: 'hang' },
  'lib_chest_supported_row': { status: 'pending', archetype: 'pull' },
  'lib_seated_cable_row': { status: 'approved' },
  'lib_barbell_row': { status: 'pending', archetype: 'pull' },
  'lib_pendlay_row': { status: 'pending', archetype: 'pull' },
  'lib_one_arm_dumbbell_row': { status: 'pending', archetype: 'pull' },
  'lib_t_bar_row': { status: 'pending', archetype: 'pull' },
  'lib_landmine_row': { status: 'pending', archetype: 'pull' },
  'lib_straight_arm_pulldown': { status: 'pending', archetype: 'hold' },
  'lib_machine_pullover': { status: 'pending', archetype: 'balance' },
  'lib_dumbbell_pullover': { status: 'pending', archetype: 'hold' },
  'lib_dumbbell_shrug': { status: 'pending', archetype: 'hold' },
  'lib_barbell_shrug': { status: 'pending', archetype: 'hold' },
  'lib_smith_machine_shrug': { status: 'pending', archetype: 'hold' },
  'lib_cable_shrug': { status: 'pending', archetype: 'hold' },
  'lib_back_extension': { status: 'pending', archetype: 'none' },
  'lib_dumbbell_biceps_curl': { status: 'pending', archetype: 'curl' },
  'lib_alternating_dumbbell_curl': { status: 'pending', archetype: 'curl' },
  'lib_barbell_curl': { status: 'pending', archetype: 'curl' },
  'lib_ez_bar_curl': { status: 'pending', archetype: 'curl' },
  'lib_hammer_curl': { status: 'pending', archetype: 'curl' },
  'lib_cross_body_hammer_curl': { status: 'pending', archetype: 'curl' },
  'lib_cable_curl': { status: 'pending', archetype: 'curl' },
  'lib_bayesian_cable_curl': { status: 'pending', archetype: 'curl' },
  'lib_preacher_curl': { status: 'pending', archetype: 'curl' },
  'lib_incline_dumbbell_curl': { status: 'pending', archetype: 'curl' },
  'lib_concentration_curl': { status: 'pending', archetype: 'curl' },
  'lib_reverse_curl': { status: 'pending', archetype: 'curl' },
  'lib_wrist_curl': { status: 'pending', archetype: 'curl' },
  'lib_leg_extension': { status: 'pending', archetype: 'balance' },
  'lib_seated_leg_curl': { status: 'pending', archetype: 'balance' },
  'lib_lying_leg_curl': { status: 'pending', archetype: 'balance' },
  'lib_standing_leg_curl': { status: 'pending', archetype: 'balance' },
  'lib_leg_press': { status: 'approved' },
  'lib_horizontal_leg_press': { status: 'pending', archetype: 'balance' },
  'lib_hack_squat': { status: 'pending', archetype: 'balance' },
  'lib_pendulum_squat': { status: 'pending', archetype: 'balance' },
  'lib_barbell_back_squat': { status: 'approved' },
  'lib_front_squat': { status: 'pending', archetype: 'on-body' },
  'lib_goblet_squat': { status: 'pending', archetype: 'on-body' },
  'lib_smith_machine_squat': { status: 'pending', archetype: 'on-body' },
  'lib_bulgarian_split_squat': { status: 'pending', archetype: 'hold' },
  'lib_walking_lunge': { status: 'pending', archetype: 'hold' },
  'lib_reverse_lunge': { status: 'pending', archetype: 'hold' },
  'lib_forward_lunge': { status: 'pending', archetype: 'hold' },
  'lib_step_up': { status: 'pending', archetype: 'hold' },
  'lib_romanian_deadlift': { status: 'pending', archetype: 'hold' },
  'lib_dumbbell_romanian_deadlift': { status: 'pending', archetype: 'hold' },
  'lib_single_leg_romanian_deadlift': { status: 'pending', archetype: 'hold' },
  'lib_conventional_deadlift': { status: 'pending', archetype: 'hold' },
  'lib_sumo_deadlift': { status: 'pending', archetype: 'hold' },
  'lib_hip_thrust': { status: 'pending', archetype: 'on-body' },
  'lib_glute_bridge': { status: 'pending', archetype: 'none' },
  'lib_cable_kickback': { status: 'pending', archetype: 'balance' },
  'lib_hip_abduction': { status: 'pending', archetype: 'balance' },
  'lib_hip_adduction': { status: 'pending', archetype: 'balance' },
  'lib_seated_calf_raise': { status: 'pending', archetype: 'balance' },
  'lib_standing_calf_raise': { status: 'pending', archetype: 'balance' },
  'lib_leg_press_calf_raise': { status: 'pending', archetype: 'balance' },
  'lib_crunch': { status: 'pending', archetype: 'none' },
  'lib_cable_crunch': { status: 'pending', archetype: 'on-body' },
  'lib_machine_crunch': { status: 'pending', archetype: 'balance' },
  'lib_resisted_hip_flexion': { status: 'pending', archetype: 'balance' },
  'lib_hanging_leg_raise': { status: 'approved' },
  'lib_hanging_knee_raise': { status: 'pending', archetype: 'hang' },
  'lib_reverse_crunch': { status: 'pending', archetype: 'none' },
  'lib_plank': { status: 'pending', archetype: 'none' },
  'lib_side_plank': { status: 'pending', archetype: 'none' },
  'lib_ab_wheel_rollout': { status: 'pending', archetype: 'push' },
  'lib_russian_twist': { status: 'pending', archetype: 'on-body' },
  'lib_pallof_press': { status: 'pending', archetype: 'hold' },
  'lib_dead_bug': { status: 'pending', archetype: 'none' },
  'lib_sled_push': { status: 'pending', archetype: 'push' },
  'lib_sled_pull': { status: 'pending', archetype: 'pull' },
  'lib_farmer_s_carry': { status: 'pending', archetype: 'hold' },
  'lib_burpee': { status: 'pending', archetype: 'palm-flat' },
  'lib_mountain_climbers': { status: 'pending', archetype: 'palm-flat' },
  'lib_jumping_jacks': { status: 'pending', archetype: 'none' },
  'lib_high_knees': { status: 'pending', archetype: 'none' },
  'lib_jump_rope': { status: 'pending', archetype: 'implement' },
  'lib_kettlebell_swing': { status: 'pending', archetype: 'implement' },
  'lib_box_jump': { status: 'pending', archetype: 'none' },
  'lib_battle_ropes': { status: 'pending', archetype: 'implement' },
  'lib_medicine_ball_slam': { status: 'pending', archetype: 'implement' },
  'lib_wall_ball': { status: 'pending', archetype: 'implement' },
  'lib_bear_crawl': { status: 'pending', archetype: 'palm-flat' },
  'lib_renegade_row': { status: 'pending', archetype: 'palm-flat' },
  'lib_bodyweight_squat': { status: 'pending', archetype: 'none' },
  'lib_jump_squat': { status: 'pending', archetype: 'none' },
  'lib_bodyweight_lunge': { status: 'pending', archetype: 'none' },
  'lib_bodyweight_split_squat': { status: 'pending', archetype: 'none' },
  'lib_pistol_squat': { status: 'pending', archetype: 'none' },
  'lib_wall_sit': { status: 'pending', archetype: 'none' },
  'lib_bodyweight_calf_raise': { status: 'pending', archetype: 'none' },
  'lib_inverted_row': { status: 'pending', archetype: 'pull' },
  'lib_pike_push_up': { status: 'pending', archetype: 'palm-flat' },
  'lib_diamond_push_up': { status: 'pending', archetype: 'palm-flat' },
  'lib_v_up': { status: 'pending', archetype: 'none' },
  'lib_bicycle_crunch': { status: 'pending', archetype: 'none' },
  'lib_flutter_kicks': { status: 'pending', archetype: 'none' },
  'lib_hollow_body_hold': { status: 'pending', archetype: 'none' },
  'lib_bird_dog': { status: 'pending', archetype: 'palm-flat' },
  'lib_superman': { status: 'pending', archetype: 'none' },
  'lib_resistance_band_row': { status: 'pending', archetype: 'pull' },
  'lib_resistance_band_pull_apart': { status: 'pending', archetype: 'pull' },
};

